### ISSUE TITLE
Improve Zendesk Documentation

### ISSUE THREAD

**Issue by cabullmann** [Cognigy/Extensions#139]
**Is your feature request related to a problem? Please describe.**
Our current documentation of the Zendesk Extension is lacking where to get the necessary input values from Zendesk, especially the client ID and secret.

**Describe the solution you'd like**
Extend the documentation to include the necessary steps, either here in Github or as an article in our helpcenter, which would be linked from the Extension readme.

**Comment by cabullmann** [comment]
> Hey @cabullmann, could you please provide a link to the used document or more information around the issue?

There is no documentation other than what is written at https://github.com/Cognigy/Extensions/tree/master/extensions/zendesk, which is exactly the issue

**Comment by cabullmann** [comment]
we do have https://support.cognigy.com/hc/en-us/articles/360021204680#h_01F3Q3XRKSAKDFATTQ28KW9SDK, however, that does not cover where to get the client ID and secret

**Comment by alexteusz** [comment]
documentation extended here: https://support.cognigy.com/hc/en-us/articles/4413935363346-Zendesk-Check-Agent-Availability-via-Zendesk-Chat-API 

issue will be closed
