### ISSUE TITLE
Update docs/examples to newest features

### ISSUE THREAD

**Issue by cabullmann** [Cognigy/Extensions#153]
We should include our new Extension features such as Tokens, Localization, etc. in our examples

**Comment by alexteusz** [comment]
Yes, we will use the Zendesk Extension and add Localization to it as an example.

**Comment by alexteusz** [comment]
The Zendesk 4.4.1 release adds an example for localization: https://github.com/Cognigy/Extensions/releases/tag/zendesk441. Furthermore, the Service Now Extension provides examples for Tokens.
