### ISSUE TITLE
Add a note to SalesForce Node

### ISSUE THREAD

**Issue by godmcse** [Cognigy/Extensions#167]
Hello, 

I been working on a solution to be able to add a Note to any salesforce entity.  I built the code to add the new node.  It has worked perfectly.  Can you please add this feature to the SalesForce-crm Extension. 

The new Node is "Add Note"  makes it easier for users to just add a note to salesforce without having to build the JSON structure.  The node has all the fields required to add a note to any entity.

Please email me and I can send over the files.

Johnny Balji
Senior Sales Engineer- North America

Mobile: 201-403-3004
Email:  J.balji@cognigy.com  
Cognigy Inc.

**Comment by alexteusz** [comment]
Will do
