### ISSUE TITLE
Google Sheets error handling and docs

### ISSUE THREAD

**Issue by rgstephens** [Cognigy/Extensions#169]
I'm trying to use the Google Sheets extension and running into some issues and questions.

- The connection field looks like it has to be in quotes, otherwise the log shows an error
- There doesn't appear to be an error reporting on invalid API key or invalid spreadsheet ID. I suspect this could be why it's not working for me.
- What's the format of the `values` field? Example?

**Comment by alexteusz** [comment]
Released with https://github.com/Cognigy/Extensions/releases/tag/google-sheets420
