### ISSUE TITLE
Google sheets `append` does `update` instead

### ISSUE THREAD

**Issue by rgstephens** [Cognigy/Extensions#172]
The Append Values node is [calling](https://github.com/Cognigy/Extensions/blob/0944270a546c0eea53fe8975bba18082f3133764/extensions/google-sheets/src/nodes/appendValues.ts#L136) `update` instead of `append`.

**Comment by alexteusz** [comment]
Released with https://github.com/Cognigy/Extensions/releases/tag/google-sheets420
